name: hive
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas
  - seaborn
  - gymnasium>=0.30.0
  - jupyterlab
  - ipykernel
  - pydantic
  - protobuf
  - absl-py
  - abseil-cpp
  - pytorch=2.2.*
  - ray=2.10.*
  - pymunk
  - pygame
